name: Feature, Fix, Hotfix, Chore Branch CI
on:
  push:
    branches: [ feat/*, fix/*, hotfix/*, chore/* ]
  workflow_dispatch:
jobs:
  code-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: code test
        run: |
          npm ci
          npm test
